#*****************************************************************************************
# Vivado (TM) v2024.2 (64-bit)
#
# create_project.tcl: Tcl script for re-creating project 'udp_filter'
#
# Generated by Vivado on Wed Dec 31 16:18:18 -0600 2025
# IP Build 5239520 on Sun Nov 10 16:12:51 MST 2024
#
# This file contains the Vivado Tcl commands for re-creating the project to the state*
# when this script was generated. In order to re-create the project, please source this
# file in the Vivado Tcl Shell.
#
# * Note that the runs in the created project will be configured the same way as the
#   original project, however they will not be launched automatically. To regenerate the
#   run results please launch the synthesis/implementation runs as needed.
#
#*****************************************************************************************
# NOTE: In order to use this script for source control purposes, please make sure that the
#       following files are added to the source control system:-
#
# 1. This project restoration tcl script (create_project.tcl) that was generated.
#
# 2. The following source(s) files that were local or imported into the original project.
#    (Please see the '$orig_proj_dir' and '$origin_dir' variable setting below at the start of the script)
#
#    "D:/HFT training/udp_filter/udp_filter.srcs/sources_1/new/udp_filter.v"
#    "D:/HFT training/udp_filter/udp_filter.srcs/sources_1/imports/HFT training/fsm/fsm.srcs/sources_1/new/packet_parser.v"
#    "D:/HFT training/udp_filter/udp_filter.srcs/sources_1/new/init_ethernet.v"
#    "D:/HFT training/udp_filter/udp_filter.srcs/sources_1/imports/HFT training/aync_fifo/aync_fifo.srcs/sources_1/new/fifomem.v"
#    "D:/HFT training/udp_filter/udp_filter.srcs/sources_1/imports/HFT training/aync_fifo/aync_fifo.srcs/sources_1/new/rptr_empty.v"
#    "D:/HFT training/udp_filter/udp_filter.srcs/sources_1/imports/HFT training/aync_fifo/aync_fifo.srcs/sources_1/new/wptr_full.v"
#    "D:/HFT training/udp_filter/udp_filter.srcs/sources_1/imports/HFT training/aync_fifo/aync_fifo.srcs/sources_1/new/sync_r2w.v"
#    "D:/HFT training/udp_filter/udp_filter.srcs/sources_1/imports/HFT training/aync_fifo/aync_fifo.srcs/sources_1/new/sync_w2r.v"
#    "D:/HFT training/udp_filter/udp_filter.srcs/sources_1/imports/HFT training/aync_fifo/aync_fifo.srcs/sources_1/new/bin2gray.v"
#    "D:/HFT training/udp_filter/udp_filter.srcs/sources_1/imports/HFT training/aync_fifo/aync_fifo.srcs/sources_1/new/gray2bin.v"
#    "D:/HFT training/udp_filter/udp_filter.srcs/sim_1/new/tb_design_1.v"
#    "D:/HFT training/udp_filter/udp_filter.srcs/sim_1/new/tb_udp_filter.v"
#
# 3. The following remote source files that were added to the original project:-
#
#    <none>
#
#*****************************************************************************************

# Check file required for this script exists
proc checkRequiredFiles { origin_dir} {
  set status true
  set files [list \
 "[file normalize "$origin_dir/udp_filter.v"]"\
 "[file normalize "$origin_dir/packet_parser.v"]"\
 "[file normalize "$origin_dir/init_ethernet.v"]"\
 "[file normalize "$origin_dir/fifomem.v"]"\
 "[file normalize "$origin_dir/rptr_empty.v"]"\
 "[file normalize "$origin_dir/wptr_full.v"]"\
 "[file normalize "$origin_dir/sync_r2w.v"]"\
 "[file normalize "$origin_dir/sync_w2r.v"]"\
 "[file normalize "$origin_dir/bin2gray.v"]"\
 "[file normalize "$origin_dir/gray2bin.v"]"\
 "[file normalize "$origin_dir/tb_design_1.v"]"\
 "[file normalize "$origin_dir/tb_udp_filter.v"]"\
  ]
  foreach ifile $files {
    if { ![file isfile $ifile] } {
      puts " Could not find local file $ifile "
      set status false
    }
  }

  return $status
}
# Set the reference directory for source file relative paths (by default the value is script directory path)
set origin_dir "."

# Use origin directory path location variable, if specified in the tcl shell
if { [info exists ::origin_dir_loc] } {
  set origin_dir $::origin_dir_loc
}

# Set the project name
set _xil_proj_name_ "udp_filter"

# Use project name variable, if specified in the tcl shell
if { [info exists ::user_project_name] } {
  set _xil_proj_name_ $::user_project_name
}

variable script_file
set script_file "create_project.tcl"

# Help information for this script
proc print_help {} {
  variable script_file
  puts "\nDescription:"
  puts "Recreate a Vivado project from this script. The created project will be"
  puts "functionally equivalent to the original project for which this script was"
  puts "generated. The script contains commands for creating a project, filesets,"
  puts "runs, adding/importing sources and setting properties on various objects.\n"
  puts "Syntax:"
  puts "$script_file"
  puts "$script_file -tclargs \[--origin_dir <path>\]"
  puts "$script_file -tclargs \[--project_name <name>\]"
  puts "$script_file -tclargs \[--help\]\n"
  puts "Usage:"
  puts "Name                   Description"
  puts "-------------------------------------------------------------------------"
  puts "\[--origin_dir <path>\]  Determine source file paths wrt this path. Default"
  puts "                       origin_dir path value is \".\", otherwise, the value"
  puts "                       that was set with the \"-paths_relative_to\" switch"
  puts "                       when this script was generated.\n"
  puts "\[--project_name <name>\] Create project with the specified name. Default"
  puts "                       name is the name of the project from where this"
  puts "                       script was generated.\n"
  puts "\[--help\]               Print help information for this script"
  puts "-------------------------------------------------------------------------\n"
  exit 0
}

if { $::argc > 0 } {
  for {set i 0} {$i < $::argc} {incr i} {
    set option [string trim [lindex $::argv $i]]
    switch -regexp -- $option {
      "--origin_dir"   { incr i; set origin_dir [lindex $::argv $i] }
      "--project_name" { incr i; set _xil_proj_name_ [lindex $::argv $i] }
      "--help"         { print_help }
      default {
        if { [regexp {^-} $option] } {
          puts "ERROR: Unknown option '$option' specified, please type '$script_file -tclargs --help' for usage info.\n"
          return 1
        }
      }
    }
  }
}

# Set the directory path for the original project from where this script was exported
set orig_proj_dir "[file normalize "$origin_dir/"]"

# Check for paths and files needed for project creation
set validate_required 0
if { $validate_required } {
  if { [checkRequiredFiles $origin_dir] } {
    puts "Tcl file $script_file is valid. All files required for project creation is accesable. "
  } else {
    puts "Tcl file $script_file is not valid. Not all files required for project creation is accesable. "
    return
  }
}

# Create project
create_project ${_xil_proj_name_} ./${_xil_proj_name_} -part xcvu37p-fsvh2892-3-e

# Set the directory path for the new project
set proj_dir [get_property directory [current_project]]

# Reconstruct message rules
# None

# Create 'sources_1' fileset (if not found)
if {[string equal [get_filesets -quiet sources_1] ""]} {
  create_fileset -srcset sources_1
}

# Set 'sources_1' fileset object
set obj [get_filesets sources_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/udp_filter.v" ]\
 [file normalize "${origin_dir}/packet_parser.v"]\
 [file normalize "${origin_dir}/init_ethernet.v" ]\
 [file normalize "${origin_dir}/fifomem.v"]\
 [file normalize "${origin_dir}/rptr_empty.v"]\
 [file normalize "${origin_dir}/wptr_full.v"]\
 [file normalize "${origin_dir}/sync_r2w.v"]\
 [file normalize "${origin_dir}/sync_w2r.v"]\
 [file normalize "${origin_dir}/bin2gray.v"]\
 [file normalize "${origin_dir}/gray2bin.v"]\
]
set imported_files ""
foreach f $files {
  lappend imported_files [import_files -fileset sources_1 $f]
}

# Set 'sources_1' fileset file properties for remote files
# None

# Set 'sources_1' fileset file properties for local files
# None

# Set 'sources_1' fileset properties
set obj [get_filesets sources_1]
set_property -name "dataflow_viewer_settings" -value "min_width=16" -objects $obj
set_property -name "top" -value "design_1_wrapper" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj

# Create 'constrs_1' fileset (if not found)
if {[string equal [get_filesets -quiet constrs_1] ""]} {
  create_fileset -constrset constrs_1
}

# Set 'constrs_1' fileset object
set obj [get_filesets constrs_1]

# Empty (no sources present)

# Set 'constrs_1' fileset properties
set obj [get_filesets constrs_1]
#set_property -name "target_part" -value "xcvu37p-fsvh2892-3-e" -objects $obj

# Create 'sim_1' fileset (if not found)
if {[string equal [get_filesets -quiet sim_1] ""]} {
  create_fileset -simset sim_1
}

# Set 'sim_1' fileset object
set obj [get_filesets sim_1]
# Import local files from the original project
set files [list \
 [file normalize "${origin_dir}/tb_design_1.v" ]\
 [file normalize "${origin_dir}/tb_udp_filter.v" ]\
]
set imported_files ""
foreach f $files {
  lappend imported_files [import_files -fileset sim_1 $f]
}

# Set 'sim_1' fileset file properties for remote files
# None

# Set 'sim_1' fileset file properties for local files
set file "new/tb_udp_filter.v"
set file_obj [get_files -of_objects [get_filesets sim_1] [list "*$file"]]
set_property -name "is_enabled" -value "0" -objects $file_obj


# Set 'sim_1' fileset properties
set obj [get_filesets sim_1]
set_property -name "sim_wrapper_top" -value "1" -objects $obj
set_property -name "top" -value "tb_full_system" -objects $obj
set_property -name "top_auto_set" -value "0" -objects $obj
set_property -name "top_lib" -value "xil_defaultlib" -objects $obj

# Set 'utils_1' fileset object
set obj [get_filesets utils_1]
# Empty (no sources present)

# Set 'utils_1' fileset properties
set obj [get_filesets utils_1]


# Adding sources referenced in BDs, if not already added
if { [get_files [list udp_filter.v]] == "" } {
  import_files -quiet -fileset sources_1 ./udp_filter.v
}
if { [get_files [list packet_parser.v]] == "" } {
  import_files -quiet -fileset sources_1 ./packet_parser.v
}
if { [get_files [list init_ethernet.v]] == "" } {
  import_files -quiet -fileset sources_1 ./init_ethernet.v
}


# Proc to create BD design_1
proc cr_bd_design_1 { parentCell } {
# The design that will be created by this Tcl proc contains the following 
# module references:
# packet_parser, udp_filter, ethernet_init



  # CHANGE DESIGN NAME HERE
  set design_name design_1

  common::send_gid_msg -ssname BD::TCL -id 2010 -severity "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK IPs
  ##################################################################
  set bCheckIPs 1
  if { $bCheckIPs == 1 } {
     set list_check_ips "\ 
  xilinx.com:ip:axi_ethernet:7.2\
  xilinx.com:ip:axis_data_fifo:2.0\
  xilinx.com:ip:clk_wiz:6.0\
  xilinx.com:ip:proc_sys_reset:5.0\
  "

   set list_ips_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2011 -severity "INFO" "Checking if the following IPs exist in the project's IP catalog: $list_check_ips ."

   foreach ip_vlnv $list_check_ips {
      set ip_obj [get_ipdefs -all $ip_vlnv]
      if { $ip_obj eq "" } {
         lappend list_ips_missing $ip_vlnv
      }
   }

   if { $list_ips_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2012 -severity "ERROR" "The following IPs are not found in the IP Catalog:\n  $list_ips_missing\n\nResolution: Please add the repository containing the IP(s) to the project." }
      set bCheckIPsPassed 0
   }

  }

  ##################################################################
  # CHECK Modules
  ##################################################################
  set bCheckModules 1
  if { $bCheckModules == 1 } {
     set list_check_mods "\ 
  packet_parser\
  udp_filter\
  ethernet_init\
  "

   set list_mods_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2020 -severity "INFO" "Checking if the following modules exist in the project's sources: $list_check_mods ."

   foreach mod_vlnv $list_check_mods {
      if { [can_resolve_reference $mod_vlnv] == 0 } {
         lappend list_mods_missing $mod_vlnv
      }
   }

   if { $list_mods_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2021 -severity "ERROR" "The following module(s) are not found in the project: $list_mods_missing" }
      common::send_gid_msg -ssname BD::TCL -id 2022 -severity "INFO" "Please add source files for the missing module(s) above."
      set bCheckIPsPassed 0
   }
}

  if { $bCheckIPsPassed != 1 } {
    common::send_gid_msg -ssname BD::TCL -id 2023 -severity "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports
  set diff_clock_rtl_0 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:diff_clock_rtl:1.0 diff_clock_rtl_0 ]
  set_property -dict [ list \
   CONFIG.FREQ_HZ {100000000} \
   ] $diff_clock_rtl_0

  set sfp_rtl_0 [ create_bd_intf_port -mode Master -vlnv xilinx.com:interface:sfp_rtl:1.0 sfp_rtl_0 ]

  set s_axis_txd_0 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 s_axis_txd_0 ]
  set_property -dict [ list \
   CONFIG.HAS_TKEEP {1} \
   CONFIG.HAS_TLAST {1} \
   CONFIG.HAS_TREADY {1} \
   CONFIG.HAS_TSTRB {0} \
   CONFIG.LAYERED_METADATA {undef} \
   CONFIG.TDATA_NUM_BYTES {4} \
   CONFIG.TDEST_WIDTH {0} \
   CONFIG.TID_WIDTH {0} \
   CONFIG.TUSER_WIDTH {0} \
   ] $s_axis_txd_0

  set s_axis_txc_0 [ create_bd_intf_port -mode Slave -vlnv xilinx.com:interface:axis_rtl:1.0 s_axis_txc_0 ]
  set_property -dict [ list \
   CONFIG.HAS_TKEEP {1} \
   CONFIG.HAS_TLAST {1} \
   CONFIG.HAS_TREADY {1} \
   CONFIG.HAS_TSTRB {0} \
   CONFIG.LAYERED_METADATA {undef} \
   CONFIG.TDATA_NUM_BYTES {4} \
   CONFIG.TDEST_WIDTH {0} \
   CONFIG.TID_WIDTH {0} \
   CONFIG.TUSER_WIDTH {0} \
   ] $s_axis_txc_0


  # Create ports
  set clk_100MHz [ create_bd_port -dir I -type clk -freq_hz 100000000 clk_100MHz ]
  set clk_100MHz_1 [ create_bd_port -dir I -type clk -freq_hz 100000000 clk_100MHz_1 ]

  # Create instance: axi_ethernet_0, and set properties
  set axi_ethernet_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axi_ethernet:7.2 axi_ethernet_0 ]
  set_property CONFIG.PHY_TYPE {1000BaseX} $axi_ethernet_0


  # Create instance: packet_parser_0, and set properties
  set block_name packet_parser
  set block_cell_name packet_parser_0
  if { [catch {set packet_parser_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $packet_parser_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: axis_data_fifo_0, and set properties
  set axis_data_fifo_0 [ create_bd_cell -type ip -vlnv xilinx.com:ip:axis_data_fifo:2.0 axis_data_fifo_0 ]
  set_property -dict [list \
    CONFIG.FIFO_DEPTH {2048} \
    CONFIG.HAS_TKEEP {1} \
    CONFIG.HAS_TLAST {1} \
    CONFIG.IS_ACLK_ASYNC {1} \
    CONFIG.TDATA_NUM_BYTES {4} \
  ] $axis_data_fifo_0


  # Create instance: udp_filter_0, and set properties
  set block_name udp_filter
  set block_cell_name udp_filter_0
  if { [catch {set udp_filter_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $udp_filter_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: clk_wiz, and set properties
  set clk_wiz [ create_bd_cell -type ip -vlnv xilinx.com:ip:clk_wiz:6.0 clk_wiz ]
  set_property CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {50.0} $clk_wiz


  # Create instance: clk_wiz_1, and set properties
  set clk_wiz_1 [ create_bd_cell -type ip -vlnv xilinx.com:ip:clk_wiz:6.0 clk_wiz_1 ]
  set_property CONFIG.CLKOUT1_REQUESTED_OUT_FREQ {100.0} $clk_wiz_1


  # Create instance: rst_clk_wiz_1_100M, and set properties
  set rst_clk_wiz_1_100M [ create_bd_cell -type ip -vlnv xilinx.com:ip:proc_sys_reset:5.0 rst_clk_wiz_1_100M ]

  # Create instance: ethernet_init_0, and set properties
  set block_name ethernet_init
  set block_cell_name ethernet_init_0
  if { [catch {set ethernet_init_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $ethernet_init_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create interface connections
  connect_bd_intf_net -intf_net axi_ethernet_0_m_axis_rxd [get_bd_intf_pins axi_ethernet_0/m_axis_rxd] [get_bd_intf_pins udp_filter_0/s_axis]
  connect_bd_intf_net -intf_net axi_ethernet_0_sfp [get_bd_intf_ports sfp_rtl_0] [get_bd_intf_pins axi_ethernet_0/sfp]
  connect_bd_intf_net -intf_net axis_data_fifo_0_M_AXIS [get_bd_intf_pins axis_data_fifo_0/M_AXIS] [get_bd_intf_pins packet_parser_0/s_axis]
  connect_bd_intf_net -intf_net diff_clock_rtl_0_1 [get_bd_intf_ports diff_clock_rtl_0] [get_bd_intf_pins axi_ethernet_0/mgt_clk]
  connect_bd_intf_net -intf_net ethernet_init_0_m_axi [get_bd_intf_pins ethernet_init_0/m_axi] [get_bd_intf_pins axi_ethernet_0/s_axi]
  connect_bd_intf_net -intf_net s_axis_txc_0_1 [get_bd_intf_ports s_axis_txc_0] [get_bd_intf_pins axi_ethernet_0/s_axis_txc]
  connect_bd_intf_net -intf_net s_axis_txd_0_1 [get_bd_intf_ports s_axis_txd_0] [get_bd_intf_pins axi_ethernet_0/s_axis_txd]
  connect_bd_intf_net -intf_net udp_filter_0_m_axis [get_bd_intf_pins udp_filter_0/m_axis] [get_bd_intf_pins axis_data_fifo_0/S_AXIS]

  # Create port connections
  connect_bd_net -net axi_ethernet_0_pma_reset_out  [get_bd_pins axi_ethernet_0/pma_reset_out] \
  [get_bd_pins clk_wiz/reset] \
  [get_bd_pins clk_wiz_1/reset] \
  [get_bd_pins rst_clk_wiz_1_100M/ext_reset_in]
  connect_bd_net -net clk_100MHz_1  [get_bd_ports clk_100MHz] \
  [get_bd_pins clk_wiz/clk_in1]
  connect_bd_net -net clk_100MHz_1_1  [get_bd_ports clk_100MHz_1] \
  [get_bd_pins clk_wiz_1/clk_in1]
  connect_bd_net -net clk_wiz_1_clk_out1  [get_bd_pins clk_wiz_1/clk_out1] \
  [get_bd_pins axis_data_fifo_0/s_axis_aclk] \
  [get_bd_pins udp_filter_0/clk] \
  [get_bd_pins rst_clk_wiz_1_100M/slowest_sync_clk] \
  [get_bd_pins axi_ethernet_0/axis_clk] \
  [get_bd_pins axi_ethernet_0/s_axi_lite_clk] \
  [get_bd_pins ethernet_init_0/clk]
  connect_bd_net -net clk_wiz_1_locked  [get_bd_pins clk_wiz_1/locked] \
  [get_bd_pins rst_clk_wiz_1_100M/dcm_locked]
  connect_bd_net -net clk_wiz_clk_out1  [get_bd_pins clk_wiz/clk_out1] \
  [get_bd_pins axi_ethernet_0/ref_clk] \
  [get_bd_pins packet_parser_0/clk] \
  [get_bd_pins axis_data_fifo_0/m_axis_aclk]
  connect_bd_net -net rst_clk_wiz_1_100M_peripheral_aresetn  [get_bd_pins rst_clk_wiz_1_100M/peripheral_aresetn] \
  [get_bd_pins axis_data_fifo_0/s_axis_aresetn] \
  [get_bd_pins axi_ethernet_0/s_axi_lite_resetn] \
  [get_bd_pins udp_filter_0/rst_n] \
  [get_bd_pins packet_parser_0/rst_n] \
  [get_bd_pins ethernet_init_0/rst_n]

  # Create address segments
  assign_bd_address -offset 0x40C00000 -range 0x00040000 -target_address_space [get_bd_addr_spaces ethernet_init_0/m_axi] [get_bd_addr_segs axi_ethernet_0/s_axi/Reg0] -force

  # Perform GUI Layout
  regenerate_bd_layout -layout_string {
   "ActiveEmotionalView":"Default View",
   "Default View_ScaleFactor":"0.503784",
   "Default View_TopLeft":"-143,-93",
   "ExpandedHierarchyInLayout":"",
   "guistr":"# # String gsaved with Nlview 7.8.0 2024-04-26 e1825d835c VDI=44 GEI=38 GUI=JA:21.0
#  -string -flagsOSRD
preplace port diff_clock_rtl_0 -pg 1 -lvl 0 -x 0 -y 300 -defaultsOSRD
preplace port sfp_rtl_0 -pg 1 -lvl 8 -x 1870 -y 270 -defaultsOSRD
preplace port s_axis_txd_0 -pg 1 -lvl 0 -x 0 -y 240 -defaultsOSRD
preplace port s_axis_txc_0 -pg 1 -lvl 0 -x 0 -y 270 -defaultsOSRD
preplace port port-id_clk_100MHz -pg 1 -lvl 0 -x 0 -y 620 -defaultsOSRD
preplace port port-id_clk_100MHz_1 -pg 1 -lvl 0 -x 0 -y 190 -defaultsOSRD
preplace inst axi_ethernet_0 -pg 1 -lvl 4 -x 930 -y 350 -defaultsOSRD
preplace inst packet_parser_0 -pg 1 -lvl 7 -x 1710 -y 160 -defaultsOSRD
preplace inst axis_data_fifo_0 -pg 1 -lvl 6 -x 1450 -y 110 -defaultsOSRD
preplace inst udp_filter_0 -pg 1 -lvl 5 -x 1200 -y 80 -defaultsOSRD
preplace inst clk_wiz -pg 1 -lvl 3 -x 660 -y 610 -defaultsOSRD
preplace inst clk_wiz_1 -pg 1 -lvl 1 -x 110 -y 180 -defaultsOSRD
preplace inst rst_clk_wiz_1_100M -pg 1 -lvl 2 -x 380 -y 150 -defaultsOSRD
preplace inst ethernet_init_0 -pg 1 -lvl 3 -x 660 -y 160 -defaultsOSRD
preplace netloc clk_wiz_clk_out1 1 3 4 760 530 NJ 530 1330 200 1570J
preplace netloc clk_wiz_1_clk_out1 1 1 5 210 50 550 230 770 160 1080 170 1310J
preplace netloc clk_wiz_1_locked 1 1 1 N 190
preplace netloc rst_clk_wiz_1_100M_peripheral_aresetn 1 2 5 560 240 790 170 1090 160 1320 210 NJ
preplace netloc clk_100MHz_1 1 0 3 NJ 620 NJ 620 NJ
preplace netloc axi_ethernet_0_pma_reset_out 1 0 5 20 110 200 310 550 540 NJ 540 1070
preplace netloc clk_100MHz_1_1 1 0 1 NJ 190
preplace netloc axis_data_fifo_0_M_AXIS 1 6 1 N 110
preplace netloc axi_ethernet_0_m_axis_rxd 1 4 1 1070 60n
preplace netloc udp_filter_0_m_axis 1 5 1 N 80
preplace netloc diff_clock_rtl_0_1 1 0 4 NJ 300 NJ 300 NJ 300 780J
preplace netloc axi_ethernet_0_sfp 1 4 4 NJ 270 NJ 270 NJ 270 NJ
preplace netloc s_axis_txd_0_1 1 0 4 20J 250 NJ 250 NJ 250 NJ
preplace netloc s_axis_txc_0_1 1 0 4 NJ 270 NJ 270 NJ 270 NJ
preplace netloc ethernet_init_0_m_axi 1 3 1 760 160n
levelinfo -pg 1 0 110 380 660 930 1200 1450 1710 1870
pagesize -pg 1 -db -bbox -sgen -150 0 1980 680
"
}

  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_design_1()

cr_bd_design_1 ""
set_property REGISTERED_WITH_MANAGER "1" [get_files design_1.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files design_1.bd ] 

if { [get_files [list fifomem.v]] == "" } {
  import_files -quiet -fileset sources_1 D:/HFT training/udp_filter/udp_filter.srcs/sources_1/imports/HFT training/aync_fifo/aync_fifo.srcs/sources_1/new/fifomem.v
}
if { [get_files [list rptr_empty.v]] == "" } {
  import_files -quiet -fileset sources_1 D:/HFT training/udp_filter/udp_filter.srcs/sources_1/imports/HFT training/aync_fifo/aync_fifo.srcs/sources_1/new/rptr_empty.v
}
if { [get_files [list wptr_full.v]] == "" } {
  import_files -quiet -fileset sources_1 D:/HFT training/udp_filter/udp_filter.srcs/sources_1/imports/HFT training/aync_fifo/aync_fifo.srcs/sources_1/new/wptr_full.v
}
if { [get_files [list sync_r2w.v]] == "" } {
  import_files -quiet -fileset sources_1 D:/HFT training/udp_filter/udp_filter.srcs/sources_1/imports/HFT training/aync_fifo/aync_fifo.srcs/sources_1/new/sync_r2w.v
}
if { [get_files [list sync_w2r.v]] == "" } {
  import_files -quiet -fileset sources_1 D:/HFT training/udp_filter/udp_filter.srcs/sources_1/imports/HFT training/aync_fifo/aync_fifo.srcs/sources_1/new/sync_w2r.v
}


# Proc to create BD async_fifo
proc cr_bd_async_fifo { parentCell } {
# The design that will be created by this Tcl proc contains the following 
# module references:
# fifomem, rptr_empty, wptr_full, sync_r2w, sync_w2r



  # CHANGE DESIGN NAME HERE
  set design_name async_fifo

  common::send_gid_msg -ssname BD::TCL -id 2010 -severity "INFO" "Currently there is no design <$design_name> in project, so creating one..."

  create_bd_design $design_name

  set bCheckIPsPassed 1
  ##################################################################
  # CHECK Modules
  ##################################################################
  set bCheckModules 1
  if { $bCheckModules == 1 } {
     set list_check_mods "\ 
  fifomem\
  rptr_empty\
  wptr_full\
  sync_r2w\
  sync_w2r\
  "

   set list_mods_missing ""
   common::send_gid_msg -ssname BD::TCL -id 2020 -severity "INFO" "Checking if the following modules exist in the project's sources: $list_check_mods ."

   foreach mod_vlnv $list_check_mods {
      if { [can_resolve_reference $mod_vlnv] == 0 } {
         lappend list_mods_missing $mod_vlnv
      }
   }

   if { $list_mods_missing ne "" } {
      catch {common::send_gid_msg -ssname BD::TCL -id 2021 -severity "ERROR" "The following module(s) are not found in the project: $list_mods_missing" }
      common::send_gid_msg -ssname BD::TCL -id 2022 -severity "INFO" "Please add source files for the missing module(s) above."
      set bCheckIPsPassed 0
   }
}

  if { $bCheckIPsPassed != 1 } {
    common::send_gid_msg -ssname BD::TCL -id 2023 -severity "WARNING" "Will not continue with creation of design due to the error(s) above."
    return 3
  }

  variable script_folder

  if { $parentCell eq "" } {
     set parentCell [get_bd_cells /]
  }

  # Get object for parentCell
  set parentObj [get_bd_cells $parentCell]
  if { $parentObj == "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2090 -severity "ERROR" "Unable to find parent cell <$parentCell>!"}
     return
  }

  # Make sure parentObj is hier blk
  set parentType [get_property TYPE $parentObj]
  if { $parentType ne "hier" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2091 -severity "ERROR" "Parent <$parentObj> has TYPE = <$parentType>. Expected to be <hier>."}
     return
  }

  # Save current instance; Restore later
  set oldCurInst [current_bd_instance .]

  # Set parent object as current
  current_bd_instance $parentObj


  # Create interface ports

  # Create ports
  set rincr_0 [ create_bd_port -dir I rincr_0 ]
  set wfull_0 [ create_bd_port -dir O wfull_0 ]
  set rdata_0 [ create_bd_port -dir O -from 7 -to 0 rdata_0 ]
  set wdata_0 [ create_bd_port -dir I -from 7 -to 0 wdata_0 ]
  set rempty_0 [ create_bd_port -dir O rempty_0 ]
  set clk_0 [ create_bd_port -dir I -type clk clk_0 ]
  set rclk_0 [ create_bd_port -dir I rclk_0 ]
  set wrst_0 [ create_bd_port -dir I wrst_0 ]
  set rwst_0 [ create_bd_port -dir I rwst_0 ]
  set wincr_0 [ create_bd_port -dir I wincr_0 ]

  # Create instance: fifomem_0, and set properties
  set block_name fifomem
  set block_cell_name fifomem_0
  if { [catch {set fifomem_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $fifomem_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: rptr_empty_0, and set properties
  set block_name rptr_empty
  set block_cell_name rptr_empty_0
  if { [catch {set rptr_empty_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $rptr_empty_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: wptr_full_0, and set properties
  set block_name wptr_full
  set block_cell_name wptr_full_0
  if { [catch {set wptr_full_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $wptr_full_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: sync_r2w_0, and set properties
  set block_name sync_r2w
  set block_cell_name sync_r2w_0
  if { [catch {set sync_r2w_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $sync_r2w_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create instance: sync_w2r_0, and set properties
  set block_name sync_w2r
  set block_cell_name sync_w2r_0
  if { [catch {set sync_w2r_0 [create_bd_cell -type module -reference $block_name $block_cell_name] } errmsg] } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2095 -severity "ERROR" "Unable to add referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   } elseif { $sync_w2r_0 eq "" } {
     catch {common::send_gid_msg -ssname BD::TCL -id 2096 -severity "ERROR" "Unable to referenced block <$block_name>. Please add the files for ${block_name}'s definition into the project."}
     return 1
   }
  
  # Create port connections
  connect_bd_net -net Net4  [get_bd_pins sync_w2r_0/rwptr] \
  [get_bd_pins rptr_empty_0/rwptr]
  connect_bd_net -net clk_0_1  [get_bd_ports clk_0] \
  [get_bd_pins fifomem_0/clk] \
  [get_bd_pins sync_r2w_0/wclk] \
  [get_bd_pins wptr_full_0/wclk]
  connect_bd_net -net fifomem_0_rdata  [get_bd_pins fifomem_0/rdata] \
  [get_bd_ports rdata_0]
  connect_bd_net -net rclk_0_1  [get_bd_ports rclk_0] \
  [get_bd_pins rptr_empty_0/rclk] \
  [get_bd_pins sync_w2r_0/rclk]
  connect_bd_net -net rincr_0_1  [get_bd_ports rincr_0] \
  [get_bd_pins rptr_empty_0/rincr]
  connect_bd_net -net rptr_empty_0_raddr  [get_bd_pins rptr_empty_0/raddr] \
  [get_bd_pins fifomem_0/raddr]
  connect_bd_net -net rptr_empty_0_rempty  [get_bd_pins rptr_empty_0/rempty] \
  [get_bd_ports rempty_0]
  connect_bd_net -net rptr_empty_0_rptr  [get_bd_pins rptr_empty_0/rptr] \
  [get_bd_pins sync_r2w_0/rptr]
  connect_bd_net -net rwst_0_1  [get_bd_ports rwst_0] \
  [get_bd_pins rptr_empty_0/rrst] \
  [get_bd_pins sync_w2r_0/rwst]
  connect_bd_net -net sync_r2w_0_wrptr  [get_bd_pins sync_r2w_0/wrptr] \
  [get_bd_pins wptr_full_0/wrptr]
  connect_bd_net -net wdata_0_1  [get_bd_ports wdata_0] \
  [get_bd_pins fifomem_0/wdata]
  connect_bd_net -net wincr_0_1  [get_bd_ports wincr_0] \
  [get_bd_pins fifomem_0/wen] \
  [get_bd_pins wptr_full_0/wincr]
  connect_bd_net -net wptr_full_0_waddr  [get_bd_pins wptr_full_0/waddr] \
  [get_bd_pins fifomem_0/waddr]
  connect_bd_net -net wptr_full_0_wfull  [get_bd_pins wptr_full_0/wfull] \
  [get_bd_ports wfull_0]
  connect_bd_net -net wptr_full_0_wptr  [get_bd_pins wptr_full_0/wptr] \
  [get_bd_pins sync_w2r_0/wptr]
  connect_bd_net -net wrst_0_1  [get_bd_ports wrst_0] \
  [get_bd_pins sync_r2w_0/wrst] \
  [get_bd_pins wptr_full_0/wrst]

  # Create address segments

  # Perform GUI Layout
  regenerate_bd_layout -layout_string {
   "ActiveEmotionalView":"Default View",
   "Default View_ScaleFactor":"0.72693",
   "Default View_TopLeft":"-139,-136",
   "ExpandedHierarchyInLayout":"",
   "guistr":"# # String gsaved with Nlview 7.8.0 2024-04-26 e1825d835c VDI=44 GEI=38 GUI=JA:21.0
#  -string -flagsOSRD
preplace port port-id_rincr_0 -pg 1 -lvl 0 -x -20 -y 260 -defaultsOSRD
preplace port port-id_wfull_0 -pg 1 -lvl 6 -x 1400 -y 220 -defaultsOSRD
preplace port port-id_rempty_0 -pg 1 -lvl 6 -x 1400 -y 150 -defaultsOSRD
preplace port port-id_clk_0 -pg 1 -lvl 0 -x -20 -y 90 -defaultsOSRD
preplace port port-id_rclk_0 -pg 1 -lvl 0 -x -20 -y 200 -defaultsOSRD
preplace port port-id_wrst_0 -pg 1 -lvl 0 -x -20 -y 120 -defaultsOSRD
preplace port port-id_rwst_0 -pg 1 -lvl 0 -x -20 -y 230 -defaultsOSRD
preplace port port-id_wincr_0 -pg 1 -lvl 0 -x -20 -y 170 -defaultsOSRD
preplace portBus rdata_0 -pg 1 -lvl 6 -x 1400 -y 330 -defaultsOSRD
preplace portBus wdata_0 -pg 1 -lvl 0 -x -20 -y 290 -defaultsOSRD
preplace inst fifomem_0 -pg 1 -lvl 5 -x 1250 -y 330 -defaultsOSRD
preplace inst rptr_empty_0 -pg 1 -lvl 4 -x 970 -y 130 -defaultsOSRD
preplace inst wptr_full_0 -pg 1 -lvl 2 -x 410 -y 100 -defaultsOSRD
preplace inst sync_r2w_0 -pg 1 -lvl 1 -x 140 -y 90 -defaultsOSRD
preplace inst sync_w2r_0 -pg 1 -lvl 3 -x 710 -y 120 -defaultsOSRD
preplace netloc Net4 1 3 1 N 120
preplace netloc clk_0_1 1 0 5 10 10 270 10 NJ 10 NJ 10 1110J
preplace netloc fifomem_0_rdata 1 5 1 NJ 330
preplace netloc rclk_0_1 1 0 4 NJ 200 NJ 200 580 200 830
preplace netloc rincr_0_1 1 0 4 0J 210 NJ 210 540J 40 830J
preplace netloc rptr_empty_0_raddr 1 4 1 1100 110n
preplace netloc rptr_empty_0_rempty 1 4 2 NJ 150 NJ
preplace netloc rptr_empty_0_rptr 1 0 5 30 220 NJ 220 530J 30 NJ 30 1090
preplace netloc rwst_0_1 1 0 4 NJ 230 NJ 230 590 210 840
preplace netloc sync_r2w_0_wrptr 1 1 1 N 90
preplace netloc wdata_0_1 1 0 5 NJ 290 NJ 290 NJ 290 NJ 290 NJ
preplace netloc wincr_0_1 1 0 5 0J 180 280 350 NJ 350 NJ 350 NJ
preplace netloc wptr_full_0_waddr 1 2 3 560J 310 NJ 310 N
preplace netloc wptr_full_0_wfull 1 2 4 550J 220 NJ 220 NJ 220 NJ
preplace netloc wptr_full_0_wptr 1 2 1 N 100
preplace netloc wrst_0_1 1 0 2 20 170 290
levelinfo -pg 1 -20 140 410 710 970 1250 1400
pagesize -pg 1 -db -bbox -sgen -160 0 1540 430
"
}

  # Restore current instance
  current_bd_instance $oldCurInst

  validate_bd_design
  save_bd_design
  close_bd_design $design_name 
}
# End of cr_bd_async_fifo()

cr_bd_async_fifo ""
set_property REGISTERED_WITH_MANAGER "1" [get_files async_fifo.bd ] 
set_property SYNTH_CHECKPOINT_MODE "Hierarchical" [get_files async_fifo.bd ] 

#call make_wrapper to create wrapper files
if { [get_property IS_LOCKED [ get_files -norecurse [list design_1.bd]] ] == 1  } {
  import_files -fileset sources_1 [file normalize "${origin_dir}/udp_filter.gen/sources_1/bd/design_1/hdl/design_1_wrapper.v" ]
} else {
  set wrapper_path [make_wrapper -fileset sources_1 -files [ get_files -norecurse [list design_1.bd]] -top]
  add_files -norecurse -fileset sources_1 $wrapper_path
}

if { [get_property IS_LOCKED [ get_files -norecurse [list async_fifo.bd]] ] == 1  } {
  import_files -fileset sources_1 [file normalize "${origin_dir}/udp_filter.gen/sources_1/bd/async_fifo/hdl/async_fifo_wrapper.v" ]
} else {
  set wrapper_path [make_wrapper -fileset sources_1 -files [ get_files -norecurse [list async_fifo.bd]] -top]
  add_files -norecurse -fileset sources_1 $wrapper_path
}


set idrFlowPropertiesConstraints ""
catch {
 set idrFlowPropertiesConstraints [get_param runs.disableIDRFlowPropertyConstraints]
 set_param runs.disableIDRFlowPropertyConstraints 1
}

# Create 'synth_1' run (if not found)
if {[string equal [get_runs -quiet synth_1] ""]} {
    create_run -name synth_1 -part xcvu37p-fsvh2892-3-e -flow {Vivado Synthesis 2024} -strategy "Vivado Synthesis Defaults" -report_strategy {No Reports} -constrset constrs_1
} else {
  set_property strategy "Vivado Synthesis Defaults" [get_runs synth_1]
  set_property flow "Vivado Synthesis 2024" [get_runs synth_1]
}
set obj [get_runs synth_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Synthesis Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'synth_1_synth_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0] "" ] } {
  create_report_config -report_name synth_1_synth_report_utilization_0 -report_type report_utilization:1.0 -steps synth_design -runs synth_1
}
set obj [get_report_configs -of_objects [get_runs synth_1] synth_1_synth_report_utilization_0]
if { $obj != "" } {

}
set obj [get_runs synth_1]
set_property -name "part" -value "xcvu37p-fsvh2892-3-e" -objects $obj
set_property -name "auto_incremental_checkpoint" -value "1" -objects $obj
set_property -name "strategy" -value "Vivado Synthesis Defaults" -objects $obj

# set the current synth run
current_run -synthesis [get_runs synth_1]

# Create 'impl_1' run (if not found)
if {[string equal [get_runs -quiet impl_1] ""]} {
    create_run -name impl_1 -part xcvu37p-fsvh2892-3-e -flow {Vivado Implementation 2024} -strategy "Vivado Implementation Defaults" -report_strategy {No Reports} -constrset constrs_1 -parent_run synth_1
} else {
  set_property strategy "Vivado Implementation Defaults" [get_runs impl_1]
  set_property flow "Vivado Implementation 2024" [get_runs impl_1]
}
set obj [get_runs impl_1]
set_property set_report_strategy_name 1 $obj
set_property report_strategy {Vivado Implementation Default Reports} $obj
set_property set_report_strategy_name 0 $obj
# Create 'impl_1_init_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_init_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps init_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_init_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_opt_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_drc_0 -report_type report_drc:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_place_report_io_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0] "" ] } {
  create_report_config -report_name impl_1_place_report_io_0 -report_type report_io:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_io_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0] "" ] } {
  create_report_config -report_name impl_1_place_report_utilization_0 -report_type report_utilization:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_place_report_control_sets_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0] "" ] } {
  create_report_config -report_name impl_1_place_report_control_sets_0 -report_type report_control_sets:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_control_sets_0]
if { $obj != "" } {
set_property -name "options.verbose" -value "1" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_incremental_reuse_1' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1] "" ] } {
  create_report_config -report_name impl_1_place_report_incremental_reuse_1 -report_type report_incremental_reuse:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_incremental_reuse_1]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj

}
# Create 'impl_1_place_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_place_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps place_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_place_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_post_place_power_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_place_power_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_place_power_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_place_power_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "is_enabled" -value "0" -objects $obj
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_drc_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0] "" ] } {
  create_report_config -report_name impl_1_route_report_drc_0 -report_type report_drc:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_drc_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_methodology_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0] "" ] } {
  create_report_config -report_name impl_1_route_report_methodology_0 -report_type report_methodology:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_methodology_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_power_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0] "" ] } {
  create_report_config -report_name impl_1_route_report_power_0 -report_type report_power:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_power_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_route_status_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0] "" ] } {
  create_report_config -report_name impl_1_route_report_route_status_0 -report_type report_route_status:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_route_status_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_route_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj

}
# Create 'impl_1_route_report_incremental_reuse_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0] "" ] } {
  create_report_config -report_name impl_1_route_report_incremental_reuse_0 -report_type report_incremental_reuse:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_incremental_reuse_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_clock_utilization_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0] "" ] } {
  create_report_config -report_name impl_1_route_report_clock_utilization_0 -report_type report_clock_utilization:1.0 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_clock_utilization_0]
if { $obj != "" } {

}
# Create 'impl_1_route_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_route_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps route_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_route_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_timing_summary_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_timing_summary_0 -report_type report_timing_summary:1.0 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_timing_summary_0]
if { $obj != "" } {
set_property -name "options.max_paths" -value "10" -objects $obj
set_property -name "options.report_unconstrained" -value "1" -objects $obj
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
# Create 'impl_1_post_route_phys_opt_report_bus_skew_0' report (if not found)
if { [ string equal [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0] "" ] } {
  create_report_config -report_name impl_1_post_route_phys_opt_report_bus_skew_0 -report_type report_bus_skew:1.1 -steps post_route_phys_opt_design -runs impl_1
}
set obj [get_report_configs -of_objects [get_runs impl_1] impl_1_post_route_phys_opt_report_bus_skew_0]
if { $obj != "" } {
set_property -name "options.warn_on_violation" -value "1" -objects $obj

}
set obj [get_runs impl_1]
set_property -name "part" -value "xcvu37p-fsvh2892-3-e" -objects $obj
set_property -name "strategy" -value "Vivado Implementation Defaults" -objects $obj
set_property -name "steps.write_bitstream.args.readback_file" -value "0" -objects $obj
set_property -name "steps.write_bitstream.args.verbose" -value "0" -objects $obj

# set the current impl run
current_run -implementation [get_runs impl_1]
catch {
 if { $idrFlowPropertiesConstraints != {} } {
   set_param runs.disableIDRFlowPropertyConstraints $idrFlowPropertiesConstraints
 }
}

puts "INFO: Project created:${_xil_proj_name_}"
# Create 'drc_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "drc_1" ] ] ""]} {
create_dashboard_gadget -name {drc_1} -type drc
}
set obj [get_dashboard_gadgets [ list "drc_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_drc_0" -objects $obj

# Create 'methodology_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "methodology_1" ] ] ""]} {
create_dashboard_gadget -name {methodology_1} -type methodology
}
set obj [get_dashboard_gadgets [ list "methodology_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_methodology_0" -objects $obj

# Create 'power_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "power_1" ] ] ""]} {
create_dashboard_gadget -name {power_1} -type power
}
set obj [get_dashboard_gadgets [ list "power_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_power_0" -objects $obj

# Create 'timing_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "timing_1" ] ] ""]} {
create_dashboard_gadget -name {timing_1} -type timing
}
set obj [get_dashboard_gadgets [ list "timing_1" ] ]
set_property -name "reports" -value "impl_1#impl_1_route_report_timing_summary_0" -objects $obj

# Create 'utilization_1' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_1" ] ] ""]} {
create_dashboard_gadget -name {utilization_1} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_1" ] ]
set_property -name "reports" -value "synth_1#synth_1_synth_report_utilization_0" -objects $obj
set_property -name "run.step" -value "synth_design" -objects $obj
set_property -name "run.type" -value "synthesis" -objects $obj

# Create 'utilization_2' gadget (if not found)
if {[string equal [get_dashboard_gadgets  [ list "utilization_2" ] ] ""]} {
create_dashboard_gadget -name {utilization_2} -type utilization
}
set obj [get_dashboard_gadgets [ list "utilization_2" ] ]
set_property -name "reports" -value "impl_1#impl_1_place_report_utilization_0" -objects $obj

move_dashboard_gadget -name {utilization_1} -row 0 -col 0
move_dashboard_gadget -name {power_1} -row 1 -col 0
move_dashboard_gadget -name {drc_1} -row 2 -col 0
move_dashboard_gadget -name {timing_1} -row 0 -col 1
move_dashboard_gadget -name {utilization_2} -row 1 -col 1
move_dashboard_gadget -name {methodology_1} -row 2 -col 1
